name: Send emails daily
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.REPOSITORY }}
          ref: ${{ vars.REF }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.5.4'

      - name: Generate email HTML
        env:
          ZOTERO_ID: ${{ secrets.ZOTERO_ID }}
          ZOTERO_KEY: ${{ secrets.ZOTERO_KEY }}
          ZOTERO_IGNORE: ${{ vars.ZOTERO_IGNORE }}
          SEND_EMPTY: ${{ vars.SEND_EMPTY }}
          ARXIV_QUERY: ${{ secrets.ARXIV_QUERY }}
          MAX_PAPER_NUM: ${{ secrets.MAX_PAPER_NUM }}
          USE_LLM_API: ${{ secrets.USE_LLM_API }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          MODEL_NAME: ${{ secrets.MODEL_NAME }}
          LANGUAGE: ${{ vars.LANGUAGE }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER: ${{ secrets.SENDER }}
          RECEIVER: ${{ secrets.RECEIVER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          MAX_PAPER_NUM: 100
        run: |
          uv run generate_email.py

      - name: Upload email artifact
        uses: actions/upload-artifact@v4
        with:
          name: email-html
          path: saved_email.html
          retention-days: 1

  send:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.REPOSITORY }}
          ref: ${{ vars.REF }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.5.4'

      - name: Download email artifact
        uses: actions/download-artifact@v4
        with:
          name: email-html

      - name: Send email
        env:
          ZOTERO_ID: placeholder
          ZOTERO_KEY: placeholder
          ARXIV_QUERY: placeholder
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER: ${{ secrets.SENDER }}
          RECEIVER: ${{ secrets.RECEIVER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        run: |
          uv run send_saved_email.py
